potter/characters/urls.py
from django.contrib import admin
from django.urls import re_path,path
from . import views

app_name = 'characters'

urlpatterns = [
    re_path(r'^(?P<character_id>[0-9]+)/$',views.detail,name='detail'),
    re_path(r'^$', views.index, name='index'),

    re_path(r'^signup/$', views.signup, name='signup'),
    re_path(r'^all_char/$', views.all_char, name='all_char'),
    re_path(r'^all_books/$', views.all_books, name='all_books'),
    re_path(r'^all_movies/$', views.all_movies, name='all_movies'),
    re_path(r'^all_movies/(?P<movie_id>[0-9]+)/$', views.movie_detail, name='movie_detail'),
    re_path(r'^all_books/(?P<book_id>[0-9]+)/$', views.book_detail, name='book_detail'),
    re_path(r'^edit/(?P<user_id>[0-9]+)/$', views.edit, name='edit'),

]

potter/potter/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path ,re_path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^characters/',include('characters.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

potter/characters/models.py
from django.db import models

# Create your models here.
class character(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    nature = models.CharField(max_length=100)
    about = models.CharField(max_length=300)
    image = models.ImageField(upload_to="all_char",blank=True)
    wiki = models.CharField(max_length=300 ,default="https://en.wikipedia.org/wiki/Harry_Potter_(film_series)")
    def __str__(self):
        return self.name+'-'+self.type




class user(models.Model):
    name = models.CharField(max_length=100)
    age = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.email+'-'+self.password+'-'+self.name


class book(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    dlink = models.CharField(max_length=500)
    year = models.CharField(max_length=5 ,default="1998")
    image = models.ImageField(upload_to="all_char",blank=True)
    synopsis = models.CharField(max_length=4800,default='op')


    def __str__(self):
        return self.name+'-'+self.year


class movie(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    trailer = models.CharField(max_length=500)
    torrent = models.CharField(max_length=500)
    year = models.CharField(max_length=4,default='2000')
    image = models.ImageField(upload_to="all_char", blank=True)
    synopsis = models.CharField(max_length=2000,default='op')
    rating = models.CharField(max_length=4,default='7.0')
    imdb = models.CharField(max_length=300 ,default="https://en.wikipedia.org/wiki/Harry_Potter_(film_series)")

    def __str__(self):
        return self.name+'-'+self.year



class bonus(models.Model):
    name = models.CharField(max_length=100)
    ebook = models.CharField(max_length=100)
    image = models.ImageField(upload_to="all_char", blank=True)
    def __str__(self):
        return self.name

potter/characters/forms.py
from django.forms import ModelForm
from .models import user

class userForm(ModelForm):

    class Meta:
        model = user
        exclude = ()

potter/characters/views.py
from django.shortcuts import render
from django.http import HttpResponse ,HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from .models import character,book,bonus
from .models import user,movie
from .forms import userForm
from django.urls import reverse

from django.contrib.auth.forms import UserCreationForm



# Create your views here.
def index(request):
    mx = {'auth':2}
    if request.method == 'POST':
        email = request.POST.get('email','')
        password = request.POST.get('password','')
        all_users = user.objects.all()
        for useri in all_users:
            list1 = str(useri).split('-')
            uemail = list1[0]
            upassword = list1[1]
            uname = list1[2]


            if(uemail==email):
                if(upassword==password):
                    val = {'auth' : 1 ,'useri':useri}
                    return render(request , 'characters/index.html',val)

                else:
                    val = {'auth' : 0}
                    return render(request , 'characters/index.html',val)
    return render(request , 'characters/index.html', mx)



def detail(request , character_id):
    return HttpResponse("<h2>Details for character:" + str(character_id)+"</h2>")


def all_char(request):
    template=loader.get_template('characters/all_char.html')
    all_characters = character.objects.all()
    context = {'all_characters': all_characters}
    return render(request,'characters/all_char.html',context)



def all_books(request):
    template=loader.get_template('characters/all_books.html')
    all_books = book.objects.all()
    a_bonus = bonus.objects.all()
    context = {'all_books': all_books,'a_bonus':a_bonus}
    return render(request,'characters/all_books.html',context)





def signup(request):
    if request.method == 'POST':
        form = userForm(request.POST)
        if form.is_valid():
            password = request.POST.get('password', '')
            cpassword = request.POST.get('cpassword', '')
            if cpassword!=password:
                form = userForm()
            else:
                form.save()
            return HttpResponseRedirect(reverse('characters:index'))
    else:
        form = userForm()
    return render(request, 'characters/signup.html' , {'form':form})



value = '0'

def all_movies(request):
    template=loader.get_template('characters/all_movies.html')
    all_movies = movie.objects.all()
    context = {'all_movies': all_movies}
    return render(request,'characters/all_movies.html',context)



def movie_detail(request , movie_id):
    dmovie = movie.objects.get(id=movie_id)
    value = movie_id
    context = {'dmovie': dmovie}

    return render(request,'characters/movie_detail.html',context)



def book_detail(request , book_id):
    dbook = book.objects.get(id=book_id)

    context = {'dbook': dbook}

    return render(request,'characters/book_detail.html',context)


def edit(request , user_id):
    uk = user.objects.get(id=user_id)
    if request.method == 'POST':
        uk = userForm(request.POST, instance=uk)
        if uk.is_valid():
            uk.save()
            return HttpResponseRedirect(reverse('characters:index'))

    return render(request, 'characters/edit.html' , {'uk':uk})

potter/characters/templates/characters/all_books.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style type="text/css">
    .card
    {
    float:left;
    margin:20px;
    color:white;
    height:900px;


    }


body
{
background-image:url("{% static 'characters/images/b_back.jpg' %}");
}

 body
        {
        font-family: "Times New Roman", Times, serif;
        }

        .jumbotron
        {
        height:200px;
        width:900px;
        }

        .bs
        {
        height:600px;
        }
    </style>

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark" id="na">
  <img class="navbar-brand" src="{% static 'characters/images/l.jpg' %}" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/characters/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " id="ml" href="/characters/all_char/">Characters</a>
      </li>

	   <li class="nav-item">
        <a class="nav-link  t" id="kl" href="/characters/all_books/">
          E-Books
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link t" href="/characters/all_movies" id="jl">
          Movies
        </a>

      </li>
    </ul>
  </div>

</nav>

{%for book in all_books%}
<div class="card bg-dark" style="width: 18rem;">
  <img src="{{book.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{book.name}}</h5>
      <ul>
          <li>{{book.year}}</li>
      </ul>
          <p>{{book.description}}<br><br>
              <a href="{{book.dlink}}" class="btn btn-primary h ">E-Book</a>
              <a href="/characters/all_books/{{book.id}}/" class="btn btn-primary h">Review</a></p>

  </div>
</div>
{%endfor%}


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


    <h1 class="display-4" style="color:white;margin-left:20px;">Bonus Section</h1>
    <p class="lead"  style="color:white;margin-left:20px;">Done with the harry potter series? No worries the magical journey doesn't end here .</p>


{%for b in a_bonus%}
<div class="card bg-dark bs" style="width: 18rem;" >
  <img src="{{b.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{b.name}}</h5>
              <a href="{{book.dlink}}" class="btn btn-primary h ">E-Book</a>


  </div>
</div>
{%endfor%}


</body></html>

potter/characters/templates/characters/all_char.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style type="text/css">
    .card
    {
    float:left;
    margin:20px;
    color:white;

    }
     body
        {
        font-family: "Times New Roman", Times, serif;
        background-image:url("{% static 'characters/images/mb12.png' %}");

        }
      .card-img-top
      {
      height:300px;
      }

    </style>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark" id="na">
  <img class="navbar-brand" src="{% static 'characters/images/l.jpg' %}" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/characters/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " id="ml" href="/characters/all_char/" style="color:white;">Characters</a>
      </li>

	   <li class="nav-item">
        <a class="nav-link  t" id="kl" href="/characters/all_books/" style="color:white;">
          E-Books
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link t" href="/characters/all_movies" id="jl" style="color:white;">
          Movies
        </a>

      </li>
    </ul>
  </div>

</nav>
{%for character in all_characters%}
<div class="card bg-dark" style="width: 18rem;">
  <img src="{{character.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{character.name}}</h5>
      <ul>
          <li>{{character.type}}</li>
          <li>{{character.nature}}</li>
      </ul>
          <p>{{character.about}}<p>
    <a href="{{character.wiki}}" class="btn btn-primary">want to know more!!!</a>
  </div>
</div>
{%endfor%}
</body></html>

potter/characters/templates/characters/all_movies.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style type="text/css">

     .card
    {
    float:left;
    margin:20px;
    color:white;
    height:900px;


    }
    .btn
    {
    margin:1px;
    float:left;
    }
    h1
    {
    margin-left:20px;
    }
    #pol
    {
    margin-left:20px;
    margin-bottom:20px;
    }
    body
        {
        font-family: "Times New Roman", Times, serif;
        background-image:url("{% static 'characters/images/mb3.jpg' %}");
        color:white;

        }
        .kol
        {
        float:left;
        margin:3px;
        }


    </style>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark" id="na">
  <img class="navbar-brand" src="{% static 'characters/images/l.jpg' %}" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/characters/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " id="ml" href="/characters/all_char/">Characters</a>
      </li>

	   <li class="nav-item">
        <a class="nav-link  t" id="kl" href="/characters/all_books/">
          E-Books
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link t" href="/characters/all_movies" id="jl">
          Movies
        </a>

      </li>
    </ul>
  </div>

</nav>
{%for movie in all_movies%}
<div class="card bg-dark" style="width: 18rem;">
  <img src="{{movie.image.url}}" class="card-img-top" alt="...">
  <div class="card-body d-flex flex-column">
    <h5 class="card-title">{{movie.name}}</h5>
      <ul>
          <li>{{movie.year}}</li>
           <li>IMDB RATING-{{movie.rating}}</li>
      </ul>
      <p>{{movie.description}}<br></p>
      <div class="card-footer " >
              <a href="{{movie.imdb}}" class="btn btn-primary kol" >IMDB</a>
           <a href="/characters/all_movies/{{movie.id}}/" class="btn btn-primary">Synopsis</a>
      </div>
  </div>
</div>
{%endfor%}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br>
<h1>Get all movies at once</h1>

<a href="https://drive.google.com/u/0/uc?id=10JUPhtkf4GxJSYtcjub5V_ZkueqeDhrq&export=download" class="btn btn-primary" id="pol">Download Torrent</a>

</body></html>

potter/characters/templates/characters/book_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Title</title>
    <style type ="text/css">
        #poster
        {
        float:left;
        width:30%;
        padding-right:20px;
        }
        p
        {
        float:left;

        margin-top:50px;
        }
        body
        {
        margin:50px;
        font-family: "Times New Roman", Times, serif;
        }
        .loo
        {
        position:relative;
        top:-14px;
        }
        hr
        {
        width:69%;
        position:relative;
        left:199px;
        }

        .ju
        {
        width:100%;
        height:80px;
        }
        #na
        {
        margin:0;
        padding:0;
        position:relative;
        top:-45px;
        left:-40px;
        }

    </style>

</head>
<body  class="text-white bg-dark">
<nav class="navbar navbar-expand-lg navbar-dark" id="na">
  <img class="navbar-brand" src="{% static 'characters/images/l.jpg' %}" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/characters/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " id="ml" href="/characters/all_char/">Characters</a>
      </li>

	   <li class="nav-item">
        <a class="nav-link  t" id="kl" href="/characters/all_books/">
          E-Books
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link t" href="/characters/all_movies" id="jl">
          Movies
        </a>

      </li>
    </ul>
  </div>

</nav>
<img src="{{dbook.image.url}}" class="card-img-top" id="poster">
<p><h1 class="display-4 loo">{{dbook.name}}</h1>
<hr color="white">
<h3>{{dbook.synopsis}}</h3><br></p>
<br><br>

<a href="{{dbook.dlink}}" class="btn btn-primary ju"><h1>Read Book</h1></a></p>
</body>
</html>

potter/characters/templates/characters/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
         body
        {
        font-family: "Times New Roman", Times, serif;
        color:white;
        }
        #sf
        {
        position:relative;
        left:150px;
        top:80px;
        }
        .form-control
        {
        width:300px;
        }
        #lp
        {
          position:relative;
        left:150px;
        top:80px;
        }

    </style>
</head>
<body class="bg-dark">
<nav class="navbar navbar-expand-lg navbar-dark" id="na">
  <img class="navbar-brand" src="{% static 'characters/images/l.jpg' %}" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/characters/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " id="ml" href="/characters/all_char/">Characters</a>
      </li>

	   <li class="nav-item">
        <a class="nav-link  t" id="kl" href="/characters/all_books/">
          E-Books
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link t" href="/characters/all_movies" id="jl">
          Movies
        </a>

      </li>
    </ul>
  </div>

</nav>


    <h1 id="lp">Edit Your Profile:</h1>


<form id="sf"  action="{% url 'characters:signup'%}" method="post">
  {% csrf_token %}
<div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
      <input type="text" name="name" class="form-control" value="{{uk.name}}" id="inputEmail3" placeholder="name">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Age</label>
    <div class="col-sm-10">
      <input type="text" name="age" value="{{uk.age}}" class="form-control" id="inputEmail3" placeholder="age">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" name="email" class="form-control" id="inputEmail3" placeholder="Email" value="{{uk.email}}">
    </div>
  </div>

  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input name="password" type="password" class="form-control" id="inputPassword3" placeholder="Password" value="{{uk.password}}">
    </div>
  </div>


   <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Confirm Password</label>
    <div class="col-sm-10">
      <input type="password" name="cpassword" class="form-control" id="inputPassword31" placeholder="Re-enter your Password">
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary" id="bh">Save</button>
    </div>
  </div>
</form>

</body>
</html>

potter/characters/templates/characters/signup.html
{% load static %}
<html>
<head>
<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<style> 



body
{
background-image:url("{% static 'characters/images/sb1.jpg' %}");
width:60%;
overflow-x:hidden;
}

#su
{
margin:auto 10px;

}

.navbar
{
	width:200%;
	
	
}

#sb{
position:relative;
top:5px;
left:715px;



}
  body
        {
        font-family: "Times New Roman", Times, serif;
        }

#footer
{
 position: fixed;
  left: 0;
  bottom: 0;
  height:40px;
  width: 100%;
color:white;
 
}
#mk
{
display:none;
}

#sf
{

width:50%;
position:relative;
top:120px;
left:300px;
}

h2
{
font-weight:strong;
 font-family: "Times New Roman", Times, serif;
position:relative;
top:100px;
left:220px;
text-align:left;
}


</style>
</head>
<body>





<nav class="navbar navbar-expand-lg navbar-dark" id="na">
  <img class="navbar-brand" src="{% static 'characters/images/l.jpg' %}" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/characters/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " id="ml" href="/characters/all_char/">Characters</a>
      </li>

	   <li class="nav-item">
        <a class="nav-link  t" id="kl" href="/characters/all_books/">
          E-Books
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link t" href="/characters/all_movies" id="jl">
          Movies
        </a>

      </li>
    </ul>
  </div>
 
</nav>






<h2>ENTER THE DETAILS TO JOIN THE DUMBLEDORE ARMY!!</h2>
<form id="sf"  action="{% url 'characters:signup'%}" method="post">
  {% csrf_token %}
<div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
      <input type="text" name="name" class="form-control" id="inputEmail3" placeholder="name">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Age</label>
    <div class="col-sm-10">
      <input type="text" name="age" class="form-control" id="inputEmail3" placeholder="age">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" name="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>

  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input name="password" type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
  
  
   <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Confirm Password</label>
    <div class="col-sm-10">
      <input type="password" name="cpassword" class="form-control" id="inputPassword31" placeholder="Re-enter your Password">
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary" onclick="event.preventDefault(); Validate();" id="bh">Sign up</button>
    </div>
  </div>
</form>
<!--


-->

<!-- Footer -->
<!-- Footer -->
<footer class="page-footer font-small" id="footer">
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3" >Developed By : Manas Khare
    <a href="https://mdbootstrap.com/education/bootstrap/"></a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
<!-- Footer -->


<script type="text/javascript">
    function Validate() {
        var password = document.getElementById("inputPassword3").value;
        var confirmPassword = document.getElementById("inputPassword31").value;
        if (password != confirmPassword) {
            alert("Passwords do not match.");
            return false;
        }
        document.getElementById("sf").submit();
        return true;
    }
</script>



</body>
</html>